language: node_js
node_js:
  - '10'

branches:
  only:
    - master

deploy:
  - provider: pages
    local-dir: out
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
